version: "3.9"

services:
    app:
        build: .
        container_name: url_shortener_app
        ports:
            - "3000:3000"
        env_file:
            - .env
        restart: unless-stopped
